[features]
seeds = false
[programs.devnet]
pstake = "2W1dtkJdDkpc2xAA1Pi7CrU7vVybvsdc3jULmFxeV8Vm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/abdullah/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
